//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonLanguages = new HashSet<PersonLanguage>();
            this.PersonQualifications = new HashSet<PersonQualification>();
            this.PersonSkills = new HashSet<PersonSkill>();
        }
    
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public string PersonSurname { get; set; }
        public string PersonCell { get; set; }
        public string PersonEmail { get; set; }
        public string CriminalRecord { get; set; }
        public int UserID { get; set; }
        public int JobID { get; set; }
<<<<<<< Updated upstream
        public int CityID { get; set; }
    
        public virtual City City { get; set; }
=======
        public int City { get; set; }
    
        public virtual Job Job { get; set; }
>>>>>>> Stashed changes
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonLanguage> PersonLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonQualification> PersonQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSkill> PersonSkills { get; set; }
    }
}
