//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qualification()
        {
<<<<<<< Updated upstream
            this.JobQualifications = new HashSet<JobQualification>();
            this.PersonQualifications = new HashSet<PersonQualification>();
=======
            this.Jobs = new HashSet<Job>();
>>>>>>> Stashed changes
        }
    
        public int QualificationID { get; set; }
        public string QualificationDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< Updated upstream
        public virtual ICollection<JobQualification> JobQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonQualification> PersonQualifications { get; set; }
=======
        public virtual ICollection<Job> Jobs { get; set; }
>>>>>>> Stashed changes
    }
}
