//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProject_272.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonQualification
    {
        public int PersonQualificationID { get; set; }
        public int PersonID { get; set; }
        public int QualificationID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
